# [next js] 에러페이지(404)

---

## [번외] 문제의 발단

- 내가 next js 블로그 프로젝트를 진행하며 다양한 페이지를 생성하며 그에 맞는 라우터, 동적 라우터 등 최대한 사용자의 모든 접근방식에 대응할 수 있도록 구현하였음

- 하지만 이에도 분명히 한계가 존재했고 아예 경로가 잘못되거나 파일이 렌더링 해줄 파일이 존재하지 않는 경로로의 접근에는 대응할 수 없음을 깨달았음

- 하지만 이러한 접근을 브라우저 자체에서 대응하는 방식이 존재하기는 함, 404 | This page could not be found.이런 식으로 화면에 렌더링 됨

- 하지만 이러한 대응은 뒤로가기 또는 홈으로 가기와 같은 사용자의 사용성을 위한 장치가 구현되어 있지 않음, 이로인해 사용자의 경험을 위해 커스텀으로 에러페이지를 구현할 수는 없을까 하는 고민을 하게됨

---

## 1. Custom404

- next js 공식문서에서는 이러한 에러페이지에 대응할 수 있는 방식을 소개하고 있었다.

- 공식문서에 의하면 프로젝트의 app폴더 내부 RootLayout과 같은 위치에 404.tsx라는 파일을 생성하고 페이지를 구성하도록 설명한다.

- 이때 404.tsx 내부는 다음과 같이 작성하라고 나온다

```js
export default function Custom404() {
  return <h1>404 - Page Not Found</h1>;
}
```

- 하지만 next js공식문서에서 설명하는데로 구현한 결과 내가 원하는데로 404페이지에 Custom404가 렌더링 되지 않았다

---

## 2. NotFound

- Custon404가 잘 작동하지 않는 것을 확인 한 후 구글을 통해 더 찾아본 결과 요즘은 구조가 좀 변경이 된듯했다

- next js가 업데이트되면서 이 부분도 업데이트가 된듯하다

- 폴더 위치는 공식문서에 나와있는 것과 동일 했지만 파일 이름과 내부 컴포넌트 이름이 변경이 된듯했다

- 제일먼저, 파일 이름이 404.tsx -> not-found.tsx로 변경이 되었다

- 그리고 내부 컴포넌트 이름은 Custom404 -> NotFound로 변경이 되었다

```js
export default function NotFound() {
  return (
    <div>
      <h1>페이지가 존재하지 않습니다</h1>
      <Link href="/">홈으로 이동</Link>
    </div>
  );
}
```

- 이런식으로 not-found를 작성한 결과 /어ㅏㅣ머리ㅏ과 같이 경로가 이상한 경우에는 정상적으로 렌더링 되는 것을 확인하였다.

- 하지만 이와같은 방식만으로는 경로는 정상적이지만 해당 글이 존재하지 않는 페이지에는 대응할 수 없었다.

---

## 3. error md

```js
export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const id = params.id;
  try {
    const filePath = path.join(
      process.cwd(),
      "src",
      "db",
      "deve",
      "md",
      `${id}.md`
    );

    const data = await fs.readFile(filePath, "utf-8");
    return NextResponse.json({ data: data }, { status: 200 });
  } catch (error) {
    return NextResponse.json({ error: "File Not Found" }, { status: 404 });
  }
}
```

- 현재 next js 서버에서는 client에서 id를 통해 데이터를 요청하면 그 id에 해당하는 md파일을 찾아 client로 보내주고 있다

- 하지만 사용자가 해당하는 md가 존재하지 않는 id로 데이터를 요청하는 경우에는 어떻게 되는 것인가?

- 다행이도 try catch문을 통해 error에 대응할 수 있었다.

- 하지만 404status와 error메세지를 보내줄 뿐 사용자의 사용성을 고려한 대응 방식은 아닌 것이다

- 사용자 입장에서는 그저 빈 화면만 렌더링 되고 무엇이 문제인지 알 수 없기 때문이다.

---

## ReactMarkDown

- 그리하여 생각한 방식이 error메시지를 데이터와 동일하게 md형식으로 보내줘서 client에서는 똑같이 md를 렌더링하는 방식이었다

- 그리하면 사용자 입장에서는 에러메시지를 눈으로 확인 할 수 있게된다. 또한 md에 링크를 추가하면 바로 홈으로 이동하거나 할 수 있게하여 사용자의 경험을 높혀준다

- 그렇게 수정한 server이다.

```js
import { NextRequest, NextResponse } from "next/server";
import path from "path";
import { promises as fs } from "fs";

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const id = params.id;
  try {
    const filePath = path.join(
      process.cwd(),
      "src",
      "db",
      "deve",
      "md",
      `${id}.md`
    );

    const data = await fs.readFile(filePath, "utf-8");
    return NextResponse.json({ data: data }, { status: 200 });
  } catch (error) {
    return NextResponse.json(
      { data: "<p>File Not Found</p>  <a href=/>cd ~</a>" },
      { status: 404 }
    );
  }
}
```

- 서버에서 다음과 같이 정삭적인 데이터 or 에러 데이터를 md형식으로 보내준다.

```js
"use client";
import { useEffect, useState } from "react";
import MarkDownView from "@/common/components/MarkDownView/MarkDownView";

function Page({ params }: { params: { id: string } }) {
  const [data, setData] = useState();
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    getData(params.id).then((res) => {
      setData(res.data);
      setVisible(true);
    });
  }, [params.id]);

  return (
    <section className={visible ? "isvisible" : "isinvisible"}>
      <article>
        <MarkDownView post={data} />
      </article>
    </section>
  );
}

const getData = async (id: string) => {
  try {
    const res = await fetch(process.env.NEXT_PUBLIC_API_URL + `craf/${id}`);
    const data = res.json();
    return data;
  } catch (e) {
    console.log(e);
  }
};

export default Page;
```

- 그렇게 서버에서 데이터를 보내주면 client에서는 정상적인 데이터인지 에러 데이터인지 굳이 구별하지 않고 렌더링만 해주면 된다

- 비정상적 경로의 404페이지, 파일이 존재하지 않는 404페이지 모두에 대응할 수 있게 되었다

- 다음에는 502처럼 더욱 다양한 에러에 대응할 수 있는 방법을 찾아야 한다
